### ISSUE TITLE
NATO is being added to any dropdown menu (inbox, reputation) and only once

### ISSUE THREAD

**Issue by tomerkal** [tomerkal/NATO-shortcut#2]
If the inbox is pressed before the review, the NATO will be added there. It will also happen once, i.e. pressing later the review button will NOT add the NATO link there as well (or instead).

version 1.1.0

**Comment by double-beep** [comment]
Hello!

The most "safe" way to add the link is to wat until a GET request to `/topbar/review` is completed. You can use [`$(document).ajaxComplete`](https://api.jquery.com/ajaxcomplete) or override the `XMLHttpRequest` prototype.

**Comment by tomerkal** [comment]
@double-beep Thanks for the recommendation. Just to make sure, this doesn't actually relate to this bug right? Is just another alternative? What's the difference between `$(document).ajaxComplete` and `$(document).on('ajaxComplete', ...)`? And see https://github.com/tomerkal/NATO-shortcut/tree/ajax-alternative where I try to implement this
